# Site settings
title: #Alexa & Echo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexaslack.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
